// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Program struct {
	ID          pgtype.UUID        `json:"id"`
	ProgramID   pgtype.UUID        `json:"program_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Service struct {
	ID          pgtype.UUID        `json:"id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Workout struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Date      pgtype.Date        `json:"date"`
	Notes     pgtype.Text        `json:"notes"`
}
