// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkout = `-- name: AddWorkout :one
INSERT INTO workouts (user_id, title, date, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, title, created_at, user_id, date, notes
`

type AddWorkoutParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
	Date   pgtype.Date `json:"date"`
	Notes  pgtype.Text `json:"notes"`
}

func (q *Queries) AddWorkout(ctx context.Context, arg AddWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, addWorkout,
		arg.UserID,
		arg.Title,
		arg.Date,
		arg.Notes,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UserID,
		&i.Date,
		&i.Notes,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts WHERE id = $1
`

func (q *Queries) DeleteWorkout(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkout, id)
	return err
}

const getWorkoutByID = `-- name: GetWorkoutByID :one
SELECT id, title, created_at, user_id, date, notes FROM workouts WHERE id = $1
`

func (q *Queries) GetWorkoutByID(ctx context.Context, id pgtype.UUID) (Workout, error) {
	row := q.db.QueryRow(ctx, getWorkoutByID, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UserID,
		&i.Date,
		&i.Notes,
	)
	return i, err
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT id, title, created_at, user_id, date, notes FROM workouts
`

func (q *Queries) ListWorkouts(ctx context.Context) ([]Workout, error) {
	rows, err := q.db.Query(ctx, listWorkouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UserID,
			&i.Date,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkoutByID = `-- name: UpdateWorkoutByID :one
UPDATE workouts
SET
	title = $2,
	date = $3,
	notes = $4
WHERE id = $1
RETURNING id, title, created_at, user_id, date, notes
`

type UpdateWorkoutByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
	Date  pgtype.Date `json:"date"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateWorkoutByID(ctx context.Context, arg UpdateWorkoutByIDParams) (Workout, error) {
	row := q.db.QueryRow(ctx, updateWorkoutByID,
		arg.ID,
		arg.Title,
		arg.Date,
		arg.Notes,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UserID,
		&i.Date,
		&i.Notes,
	)
	return i, err
}
