// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWorkout(ctx context.Context, arg AddWorkoutParams) (Workout, error)
	DeleteWorkout(ctx context.Context, id pgtype.UUID) error
	GetWorkoutByID(ctx context.Context, id pgtype.UUID) (Workout, error)
	ListWorkouts(ctx context.Context) ([]Workout, error)
	UpdateWorkoutByID(ctx context.Context, arg UpdateWorkoutByIDParams) (Workout, error)
}

var _ Querier = (*Queries)(nil)
